[package]
name = "rust-actix-skeleton"
version = "0.1.0"
authors = ["SithEngineer <sithengineer@pm.me>"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
actix-rt = "1"